version: '3.0'
# docker-compose version

# servicices / containers to be run
services: 
  angular:
    build: angular
    ports:
      - "4200:4200"
  
  express-server:
    build: express-server
    ports: 
      - "3000:3000"
    links:
      - database

  database: 
    image: mongo
    ports:
      - "27017:27017"
