version: '3'

services: 
  angular_server:
    build: angular_server
    expose:
      - 4200
    ports:
      - "4200:4200"
    container_name: angular_container
    restart: always
    links:
      - express_server
  
  express_server:
    build: express_server
    expose: 
      - 3000
    ports: 
      - "3000:3000"
    depends_on: 
      - database
    container_name: express_server_container
    restart: always
    links:
      - database

  database: 
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    container_name: database-container
    restart: always

  angular_test:
    build: angular_server
    expose:
      - 4201
    ports:
      - "4201:4200"
    container_name: angular_test_container
    restart: always
    links:
      - express_server


