version: '3'

services: 
  angular:
    build: angular
    expose:
      - 4200
    ports:
      - "4200:4200"
    container_name: angular-container
    restart: always
    links:
      - server
  
  server:
    build: server
    expose: 
      - 3000
    ports: 
      - "3000:3000"
    depends_on: 
      - database
    container_name: server-container
    restart: always
    links:
      - database

  database: 
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    container_name: database-container
    restart: always


